### ISSUE TITLE
[Bug]: MKS PI-TS35 display resolution problem with dtb replacing

### ISSUE THREAD

**Issue by karabas2011** [redrathnure/armbian-mkspi#38] opened 2024-12-18 14:11 UTC
### What happened?

I have some kingroon KLP1 printers with motherboard Cheetah-V2.2 ( rp3328 + MCU GD32F303 + THR rp2040) with
MKS PI-TS35 display. and AP6212 wifi module.
It is modified MKSPI software inside ( old debian busty, python 3.7 without ability to upgrade)
I flashed image Armbian-unofficial_25.02.0-trunk_Mkspi_bookworm_current_6.6.65.img.
I installed last klipper+moonraker+KlipperScreen.
Then I flashed both MSUs.
Display shows good image.

But no touchscreen reactions.

Then I replaced rp3328-mkspi.dtb with renamed stock rp3328-roc-cc.dtb
I got smaller image on screen (as if it is 2.5") and very seldom and random actions on touch.
I unpacked both dtb and compared. They are different and I dont know what to copypast.
If I do some - it warns about duplicate phandle
I tried original mkspi dtb with rotated screen. It shows rotated screen in smaller resolution as kingroon's one
Wierd.  Resolution setting is somewhere in dtb  

### How to reproduce?

see above

### Branch

main (main development branch)

### On which host OS are you running the build script and observing this problem?

Debian 12 Bookworm

### Are you building on Windows WSL2?

- [ ] Yes, my Ubuntu/Debian/OtherOS is running on WSL2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by redrathnure** [comment] 2024-12-18 20:29
Assuming it's duplicate of https://github.com/redrathnure/armbian-mkspi/issues/37

**Closed** 2024-12-20 08:59 UTC
